server:
  port: 10010

spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: ${mata.nacos.server-addr}
      discovery:
        username: ${mata.nacos.username}
        password: ${mata.nacos.password}
    gateway:
      routes: #网关路由配置
        - id: producer-server #路由id，自定义，只要唯一即可
          uri: lb://producer-server #路由的目标位置
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/producer/** # 路径断言 这个是按照路径匹配，只要以/producer/开头就符合要求
        - id: consumer-server
          uri: lb://consumer-server
          predicates:
            - Path=/consumer/**
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://xxxx:xxxx"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
